### ISSUE TITLE
Mushroom Kingdom U - Song doesn't Save in My Music

### ISSUE THREAD

**Issue by ghost** [matt-marek/sm4sh-mod-collection#10]
The last song in My Music doesn't save in My Music, resulting it in being "unplayable" in actual gameplay. This may be related to the issue that causes songs to not load during gameplay, and may be an issue with limits on how many songs can be added to a stage.

**Comment by matt-marek** [comment]
Issue was with an incorrect name in the song database. It was pointing to an incorrectly named file. Issue resolved.
