### ISSUE TITLE
Little Mac - Voice and SFX Issues

### ISSUE THREAD

**Issue by ghost** [matt-marek/sm4sh-mod-collection#2]
When playing with any of the additional hoodie costumes for Little Mac, in the same match as a standard, non-hooded Little Mac (original costumes), the standard (original costume) Little Mac has no voice or SFX. This might require removing voice from the additional Little Mac costumes, in order to keep voice and SFX on standard costumes and still have SFX (but no voice) for additional Little Mac costumes.

**Comment by matt-marek** [comment]
Restored nus3bank files for Little Mac and Wireframe Mac. This results in the extra Little Mac costumes being voiceless, but at least he has sound effects for punching, movement, and Doc Louis. I will look into give all Little Mac costumes a voice at a later time.
