### ISSUE TITLE
DLC - DLC Characters Unlocked as Result of CSS Organization

### ISSUE THREAD

**Issue by ghost** [matt-marek/sm4sh-mod-collection#8]
This may or may not end up being an "issue," but the characters that are marked "DLC" are now unlocked (even for those who don't own the DLC) as a result of re-arranging the CSS. If possible, this will be undone while maintaining a "cleaned up" CSS, but it may not be possible to have both.

I will attempt to either re-lock the DLC, and maintain the organization OR find a way to also unlock the stage DLC, and just have ALL DLC unlocked.

**Comment by jc5504** [comment]
If you plan on releasing this mod on Gamebanana, they dont allow mods with free dlc. If you want, you could have 2 version of the pack (one with dlc, one without), but only the version without dlc can be shared to gamebanana. I dont think sm4shmods.com has the same standards, so maybe you can get away with it there.

**Comment by matt-marek** [comment]
I'll probably just host it from my own website, since I don't really care for sm4shmods.com... Besides the size of the mod pack will be well over 1GB, maybe 2GB, which would mean horrid download times. I'm probably just going to use MEGA.
